In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences c:/Users/Naruto/AppData/Local/Programs/Python/Python38/python.exe -m pip install ipykernel -U --user --force-reinstall
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
one_hot("the",voc_size)

[3190]

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3190, 2066, 4447, 4531],
 [3190, 2066, 4447, 2937],
 [3190, 760, 4447, 7728],
 [3764, 8500, 9152, 5352, 2899],
 [3764, 8500, 9152, 5352, 866],
 [461, 3190, 2178, 4447, 3452],
 [2929, 5077, 2331, 5352]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3190 2066 4447 4531]
 [   0    0    0    0 3190 2066 4447 2937]
 [   0    0    0    0 3190  760 4447 7728]
 [   0    0    0 3764 8500 9152 5352 2899]
 [   0    0    0 3764 8500 9152 5352  866]
 [   0    0    0  461 3190 2178 4447 3452]
 [   0    0    0    0 2929 5077 2331 5352]]


In [11]:
## feature representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 49ms/step


array([[[ 6.67570904e-03,  8.80044699e-03, -1.89937837e-02,
         -3.62903997e-03, -1.72816515e-02,  4.32027690e-02,
         -2.77325045e-02, -4.60526347e-02,  3.91631834e-02,
         -7.43818283e-03],
        [ 6.67570904e-03,  8.80044699e-03, -1.89937837e-02,
         -3.62903997e-03, -1.72816515e-02,  4.32027690e-02,
         -2.77325045e-02, -4.60526347e-02,  3.91631834e-02,
         -7.43818283e-03],
        [ 6.67570904e-03,  8.80044699e-03, -1.89937837e-02,
         -3.62903997e-03, -1.72816515e-02,  4.32027690e-02,
         -2.77325045e-02, -4.60526347e-02,  3.91631834e-02,
         -7.43818283e-03],
        [ 6.67570904e-03,  8.80044699e-03, -1.89937837e-02,
         -3.62903997e-03, -1.72816515e-02,  4.32027690e-02,
         -2.77325045e-02, -4.60526347e-02,  3.91631834e-02,
         -7.43818283e-03],
        [ 3.86330746e-02,  3.34822573e-02, -3.37214023e-02,
          4.74307053e-02,  3.88586186e-02, -6.62505627e-04,
         -1.42586455e-02,  2.74634846e-02,  6.393529

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 3190, 2066, 4447, 4531])

In [21]:
prediction = model.predict(embedded_docs[0])

1/1 [==============================] - 0s 9ms/step


In [22]:
type(prediction)

numpy.ndarray

In [23]:
prediction.shape

(8, 10)

In [24]:
prediction

array([[ 6.67570904e-03,  8.80044699e-03, -1.89937837e-02,
        -3.62903997e-03, -1.72816515e-02,  4.32027690e-02,
        -2.77325045e-02, -4.60526347e-02,  3.91631834e-02,
        -7.43818283e-03],
       [ 6.67570904e-03,  8.80044699e-03, -1.89937837e-02,
        -3.62903997e-03, -1.72816515e-02,  4.32027690e-02,
        -2.77325045e-02, -4.60526347e-02,  3.91631834e-02,
        -7.43818283e-03],
       [ 6.67570904e-03,  8.80044699e-03, -1.89937837e-02,
        -3.62903997e-03, -1.72816515e-02,  4.32027690e-02,
        -2.77325045e-02, -4.60526347e-02,  3.91631834e-02,
        -7.43818283e-03],
       [ 6.67570904e-03,  8.80044699e-03, -1.89937837e-02,
        -3.62903997e-03, -1.72816515e-02,  4.32027690e-02,
        -2.77325045e-02, -4.60526347e-02,  3.91631834e-02,
        -7.43818283e-03],
       [ 3.86330746e-02,  3.34822573e-02, -3.37214023e-02,
         4.74307053e-02,  3.88586186e-02, -6.62505627e-04,
        -1.42586455e-02,  2.74634846e-02,  6.39352947e-03,
        -4.